swagger: "2.0"
info:
  description: "Serviço de Cadastro de Prestadores"
  version: "1.0.0"
  title: "Serviço de Cadastro de Prestadores"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "petconnect@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "petconnect.com.br"
basePath: "/v1"
tags:
- name: "prestador"
  description: "Gerenciamento de Prestadores"
schemes:
- "https"
- "http"
paths:
  /prestador:
    post:
      tags:
      - "prestador"
      summary: "Adiciona um novo prestador ao sistema"
      description: ""
      operationId: "criarPrestador"
      consumes:
      - "application/json"
      - "application/xml"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - in: "body"
        name: "dados do prestador"
        description: "Informações de cadastro do prestador"
        required: true
        schema:
          $ref: "#/definitions/Prestador"
      responses:
        "405":
          description: "Invalid input"
    get:
      tags:
      - "prestador"
      summary: "Exibe a lista de prestadores"
      description: "Retorna uma lista de prestadores"
      operationId: "getAllPrestadores"
      produces:
      - "application/xml"
      - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Prestador"          
  /prestador/{cnpj}:
    get:
      tags:
      - "prestador"
      summary: "Busca um prestador por CNPJ"
      description: "Retorna um único prestador"
      operationId: "getPrestadorByCnpj"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "cnpj"
        in: "path"
        description: "CNPJ do prestador"
        required: true
        type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Prestador"
        "400":
          description: "CNPJ inválido"
        "404":
          description: "Prestador de serviço não encontrado"
    put:
      tags:
      - "prestador"
      summary: "Altera o cadastro de um prestador existente"
      description: ""
      operationId: "updatePrestador"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "cnpj"
        in: "path"
        description: "CNPJ do prestador a ser alterado no sistema"
        required: true
        type: "string"
      - in: "body"
        name: "body"
        description: "Atualização do prestador"
        required: true
        schema:
          $ref: "#/definitions/Prestador"
      responses:
        "400":
          description: "CNPJ inválido"
        "404":
          description: "Prestador não encontrado"
    delete:
      tags:
      - "prestador"
      summary: "Exclui um prestador"
      description: ""
      operationId: "deletePrestador"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "cnpj"
        in: "path"
        description: "CNPJ do prestador para excluir"
        required: true
        type: "string"
      responses:
        "400":
          description: "CNPJ inválido"
        "404":
          description: "Prestador não encontrado"
definitions:
  Prestador:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      cnpj:
        type: "string"
      tipo:
        type: "string"
        description: "Tipo de Prestador"
        enum:
        - "veterinario"
        - "pet shop"
      nome:
        type: "string"
      email:
        type: "string"
      usuario:
        type: "string"
      senha:
        type: "string"
      endereco:
        $ref: "#/definitions/Endereco"
      contato:
        $ref: "#/definitions/Contato"
    xml:
      name: "Prestador"
  Endereco:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      logradouro:
        type: "string"
      numero:
        type: "integer"
      bairro:
        type: "string"
      cidade:
        type: "string"
      uf:
        type: "string"
    xml:
      name: "Endereco"
  Contato:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      telefone:
        type: "string"
    xml:
      name: "Contato"
