swagger: "2.0"
info:
  description: "Cadastro de Serviços do PetConnect"
  version: "1.0.0"
  title: "Serviço de Cadastro de Serviços"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "petconnect@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "petconnect.com.br"
basePath: "/v1"
tags:
- name: "servico"
  description: "Gerenciamento de Serviços"
schemes:
- "https"
- "http"
paths:
  /servico:
    post:
      tags:
      - "servico"
      summary: "Adiciona um novo serviço ao sistema"
      description: ""
      operationId: "criarServico"
      consumes:
      - "application/json"
      - "application/xml"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Informações de cadastro do serviço"
        required: true
        schema:
          $ref: "#/definitions/Servico"
      responses:
        "405":
          description: "Invalid input"
    get:
      tags:
      - "servico"
      summary: "Exibe a lista de serviços cadastrados"
      description: "Retorna uma lista de serviços"
      operationId: "getAllServicos"
      produces:
      - "application/xml"
      - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Servico"
  /servico/{descricao}:
    get:
      tags:
      - "servico"
      summary: "Encontra um serviço pela descrição"
      description: ""
      operationId: "getServicoBydDescricao"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "descricao"
        in: "path"
        description: "Descrição do serviço para retornar"
        required: true
        type: "string"
      responses:
        "200":
          description: "Operação realizada com sucesso."
          schema:
            $ref: "#/definitions/Servico"
        "400":
          description: "Descrição inválida"
        "404":
          description: "Serviço não encontrado"
    put:
      tags:
      - "servico"
      summary: "Altera um serviço existente"
      description: ""
      operationId: "updateServico"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "descricao"
        in: "path"
        description: "Serviço a ser alterado no sistema"
        required: true
        type: "string"
      - in: "body"
        name: "body"
        description: "Atualização do serviço"
        required: true
        schema:
          $ref: "#/definitions/Servico"
      responses:
        "400":
          description: "Descrição inválida"
        "404":
          description: "Serviço não encontrado"
    delete:
      tags:
      - "servico"
      summary: "Exclui um serviço"
      description: ""
      operationId: "deleteServico"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "descricao"
        in: "path"
        description: "Descrição do serviço para excluir"
        required: true
        type: "string"
      responses:
        "400":
          description: "Descrição inválida"
        "404":
          description: "Serviço não encontrado"
definitions:
  Servico:
    type: "object"
    required:
    - "descricao"
    - "tipo"
    properties:
      id:
        type: "integer"
        format: "int64"
      descricao:
        type: "string"
      tipo:
        type: "string"
        description: "Tipo do Serviço"
        enum:
        - "veterinario"
        - "banho"
        - "tosa"
        - "exame clínico"
      valor:
        type: "string"
      tempomedio:
        type: "string"
    xml:
      name: "Servico"
